(name: string)
(port_as_string: string, data: dt.Datum)
(port: string, s: string)
(message: Message)
(port : string)
(msg: Message)
(eh: ^Eh, port: string, datum: dt.Datum)
(eh: ^Eh, port: string, data: $Data)
(eh: ^Eh, message: Message, instance_data: ^any)
(eh: ^Eh, state: $State)
(eh: ^Eh)
(fifo: FIFO)
(q: ^FIFO)
(iter: ^FIFO_Iterator)
(c: Connector, message: Message)
(container: ^Eh)
(container: ^Eh, from: ^Eh, message: Message)
(container: ^Eh)
(eh: ^Eh)
(eh: ^Eh)
