
  string [kb1 cs* ke] = ‛«kb1»«cs»«ke»’
  charconst [kb2 cs* ke] = ‛«kb2»«cs»«ke»’
  id [kb3 cs* ke] = ‛«kb3»«cs»«ke»’
  integer [kb4 cs* ke] = ‛«kb4»«cs»«ke»’
  symbol [kb5 cs* ke] = ‛«kb5»«cs»«ke»’
  keyword [kb6 cs* ke] = ‛«kb6»«cs»«ke»’
  multi_char_operator [kb7 cs* ke] = ‛«kb7»«cs»«ke»’
  verbatim [kb8 cs* ke] = ‛«kb8»«cs»«ke»’
  comment [kb9 cs* ke] = ‛«kb9»«cs»«ke»’
  anyToken [anyToken1] = ‛«anyToken1»’
  annotation [ab cs* ae] = ‛«ab»«cs»«ae»’
  
  ws [wsc*] = ‛«wsc»’

  sym [kbegin text kend] = ‛«kbegin»«text»«kend»’

  indentc [k] = ‛«k»’
  dedentc [k] = ‛«k»’

