(declaim (optimize (debug 3) (safety 3) (speed 0)))
(ql:quickload "uiop")
(ql:quickload "cl-json")
(defparameter *root* "/Users/tarvydas/quicklisp/local-projects/0dv2/cl/")
(load (format nil "~a~a" *root* "operand.lisp"))
(load (format nil "~a~a" *root* "fifo.lisp"))
(load (format nil "~a~a" *root* "test-fifo.lisp"))
;; (load (format nil "~a~a" *root* "0d.lisp"))
;; (load (format nil "~a~a" *root* "registry.lisp"))
;; (load (format nil "~a~a" *root* "read-json-graph.lisp"))
;; (load (format nil "~a~a" *root* "main.lisp"))
